"""
Fine-tune a RoBERTa-based binary classifier on TweepFake to detect
AI/bot-generated tweets vs. human tweets.

Dataset: https://www.kaggle.com/datasets/mtesconi/twitter-deep-fake-text
Pre-made splits (recommended over making your own):
    https://github.com/tizfa/tweepfake_deepfake_text_detection/tree/master/data/splits

CAVEAT: the "bot" class here was generated by older techniques (Markov
chains, RNN, LSTM, GPT-2) collected in 2020 -- not modern LLMs. A model
trained on this will likely underperform on tweets written by GPT-4/Claude/
etc. Treat this as a domain-matched starting point, not a finished detector
for today's AI-generated political content specifically.

Usage:
    pip install torch transformers scikit-learn pandas datasets accelerate
    python fine_tune_detector.py

Expects train.csv / val.csv / test.csv (or a single CSV you split yourself)
with columns for tweet text and a label (human/bot). Update COLUMN NAMES
below once you've downloaded the actual files and checked their headers --
I have not been able to inspect the real files in this environment.
"""

import torch
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import (
    RobertaTokenizerFast,
    RobertaForSequenceClassification,
    Trainer,
    TrainingArguments,
)
from datasets import Dataset

# --- CONFIG: update these after inspecting the actual downloaded files ---
TRAIN_CSV = "data\train.csv"
VAL_CSV = "data\val.csv"
TEST_CSV = "data\test.csv"
TEXT_COLUMN = "text"  # confirm actual column name in the CSV
LABEL_COLUMN = "account.type"  # confirm actual column name -- TweepFake uses this in the original repo
HUMAN_VALUE = "human"  # confirm actual label string/value
BOT_VALUE = "bot"  # confirm actual label string/value

MODEL_NAME = "roberta-base"
OUTPUT_DIR = "./tweepfake-detector"
MAX_LENGTH = 128  # tweets are short; 128 tokens is generous headroom
NUM_EPOCHS = 3
BATCH_SIZE = 16


def load_and_prepare(csv_path: str) -> Dataset:
    df = pd.read_csv(csv_path)
    df = df[[TEXT_COLUMN, LABEL_COLUMN]].dropna()
    df["label"] = df[LABEL_COLUMN].map({HUMAN_VALUE: 0, BOT_VALUE: 1})
    df = df.dropna(subset=["label"])  # drop rows where label mapping failed
    df["label"] = df["label"].astype(int)
    return Dataset.from_pandas(df[[TEXT_COLUMN, "label"]].reset_index(drop=True))


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}


def main():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")
    if device == "cuda":
        print(f"  GPU: {torch.cuda.get_device_name(0)}")
    else:
        print(
            "  WARNING: no GPU detected by torch -- this will be slow. "
            "If you expected a GPU here, check your torch install "
            "(may need the CUDA-enabled build, not the CPU-only one)."
        )

    tokenizer = RobertaTokenizerFast.from_pretrained(MODEL_NAME)

    print("Loading datasets...")
    train_ds = load_and_prepare(TRAIN_CSV)
    val_ds = load_and_prepare(VAL_CSV)
    test_ds = load_and_prepare(TEST_CSV)
    print(f"  train: {len(train_ds)}  val: {len(val_ds)}  test: {len(test_ds)}")

    def tokenize_fn(batch):
        return tokenizer(
            batch[TEXT_COLUMN],
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH,
        )

    train_ds = train_ds.map(tokenize_fn, batched=True)
    val_ds = val_ds.map(tokenize_fn, batched=True)
    test_ds = test_ds.map(tokenize_fn, batched=True)

    model = RobertaForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        fp16=(
            device == "cuda"
        ),  # mixed precision -- meaningful speedup on GPU, unsupported on CPU
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
    )

    print("Fine-tuning...")
    trainer.train()

    print("\nEvaluating on held-out test set...")
    test_results = trainer.evaluate(test_ds)
    print(test_results)

    print(f"\nSaving model to {OUTPUT_DIR}")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)


if __name__ == "__main__":
    main()
